/**
 * PDF Footer Generator
 * Generates footers on all pages
 */

import { addText } from '../utils/pdfHelpers';
import { colors, fontSizes } from '../styles/pdfStyles';

/**
 * Add footer to all pages in the PDF
 */
export function generateFooter(pdf: any, pageWidth: number, pageHeight: number): void {
  const totalPages = pdf.getNumberOfPages();
  
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    const footerY = pageHeight - 8;
    pdf.setFontSize(fontSizes.footer);
    pdf.setFont('helvetica', 'italic');
    pdf.setTextColor(...colors.veryLightGray);
    addText(
      pdf,
      'Generated by ScanToSplit.ai - AI-Powered Bill Splitting',
      pageWidth / 2,
      footerY,
      { align: 'center' }
    );
    pdf.setTextColor(...colors.black);
  }
}
